import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  "https://jvdlebcqfnlshgqyvgor.supabase.co",
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2ZGxlYmNxZm5sc2hncXl2Z29yIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTY5OTE4OCwiZXhwIjoyMDkxMjc1MTg4fQ.D1V5YJSAo5hrhsJtG3366YOocs0tqcHTwTbxdPqlnOY",
  { auth: { autoRefreshToken: false, persistSession: false } }
);

const restaurants = [
  // ── Vancouver ──────────────────────────────────────────────────────────────
  { name: "Farmer's Apprentice",  address: "1535 W 6th Ave, Vancouver, BC",            city: "Vancouver",    lat: 49.2665, lng: -123.1412, rating: 4.7, website: "https://farmersapprentice.ca",       price_level: 3, indie_score: 12, positive_hits: ["farm-to-table","locally sourced","seasonal menu","our farmers"], negative_hits: [], supplier_hits: ["bc farmers"],                    data_sources: ["website_main","website_about"], verdict: "🟢 Very Likely Independent" },
  { name: "Burdock & Co",         address: "2702 Main St, Vancouver, BC",              city: "Vancouver",    lat: 49.2600, lng: -123.1011, rating: 4.6, website: "https://burdockandco.com",           price_level: 3, indie_score: 11, positive_hits: ["foraged","locally sourced","organic","seasonal menu","heritage breed"], negative_hits: [], supplier_hits: [],                           data_sources: ["website_main","website_about"], verdict: "🟢 Very Likely Independent" },
  { name: "The Acorn",            address: "3995 Main St, Vancouver, BC",              city: "Vancouver",    lat: 49.2492, lng: -123.1013, rating: 4.5, website: "https://theacornrestaurant.ca",      price_level: 3, indie_score: 10, positive_hits: ["locally sourced","seasonal menu","organic","chef-driven"], negative_hits: [], supplier_hits: [],                           data_sources: ["website_main"],                 verdict: "🟢 Very Likely Independent" },
  { name: "Fable Kitchen",        address: "1944 W 4th Ave, Vancouver, BC",            city: "Vancouver",    lat: 49.2676, lng: -123.1480, rating: 4.4, website: "https://fablekitchen.ca",            price_level: 3, indie_score:  8, positive_hits: ["farm-to-table","locally sourced","chef-driven","seasonal ingredients"], negative_hits: [], supplier_hits: [],             data_sources: ["website_main","website_about"], verdict: "🟡 Probably Independent" },
  { name: "Ask For Luigi",        address: "305 Alexander St, Vancouver, BC",          city: "Vancouver",    lat: 49.2832, lng: -123.0973, rating: 4.5, website: "https://askforluigi.com",            price_level: 2, indie_score:  6, positive_hits: ["seasonal menu","house-made","local farms"], negative_hits: [], supplier_hits: [],                                data_sources: ["website_main"],                 verdict: "🟡 Probably Independent" },

  // ── Calgary ────────────────────────────────────────────────────────────────
  { name: "River Café",           address: "25 Prince's Island Park, Calgary, AB",     city: "Calgary",      lat: 51.0506, lng: -114.0653, rating: 4.7, website: "https://river-cafe.com",             price_level: 4, indie_score: 14, positive_hits: ["farm-to-table","locally sourced","alberta grown","foraged","our farmers","seasonal menu"], negative_hits: [], supplier_hits: ["olsberg farms","sunworks farm"], data_sources: ["website_main","website_about"], verdict: "🟢 Very Likely Independent" },
  { name: "Model Milk",           address: "308 17 Ave SW, Calgary, AB",               city: "Calgary",      lat: 51.0383, lng: -114.0862, rating: 4.5, website: "https://modelmilk.ca",               price_level: 3, indie_score:  9, positive_hits: ["locally sourced","seasonal menu","house-made","chef-driven"], negative_hits: [], supplier_hits: [],              data_sources: ["website_main","website_about"], verdict: "🟡 Probably Independent" },
  { name: "Charbar",              address: "618 Confluence Way SE, Calgary, AB",        city: "Calgary",      lat: 51.0436, lng: -114.0505, rating: 4.4, website: "https://charbar.ca",                 price_level: 3, indie_score:  7, positive_hits: ["locally sourced","seasonal ingredients","chef-driven"], negative_hits: [], supplier_hits: [],                      data_sources: ["website_main"],                 verdict: "🟡 Probably Independent" },
  { name: "The Guild",            address: "100 7 Ave SW, Calgary, AB",                city: "Calgary",      lat: 51.0468, lng: -114.0716, rating: 4.2, website: "https://theguildcalgary.com",         price_level: 3, indie_score:  5, positive_hits: ["seasonal menu","locally sourced","craft beer"], negative_hits: [], supplier_hits: [],                           data_sources: ["website_main"],                 verdict: "🟡 Probably Independent" },

  // ── Edmonton ───────────────────────────────────────────────────────────────
  { name: "RGE RD",               address: "10643 123 St NW, Edmonton, AB",            city: "Edmonton",     lat: 53.5547, lng: -113.5072, rating: 4.7, website: "https://rgerd.ca",                   price_level: 4, indie_score: 14, positive_hits: ["farm-to-table","locally sourced","alberta grown","our farmers","foraged","pasture-raised"], negative_hits: [], supplier_hits: ["natures green acres","sunworks farm"], data_sources: ["website_main","website_about"], verdict: "🟢 Very Likely Independent" },
  { name: "Three Boars Eatery",   address: "8424 109 St NW, Edmonton, AB",             city: "Edmonton",     lat: 53.5213, lng: -113.5147, rating: 4.5, website: "https://threeboars.ca",               price_level: 2, indie_score:  8, positive_hits: ["locally sourced","seasonal menu","house-made","craft beer"], negative_hits: [], supplier_hits: [],             data_sources: ["website_main","website_about"], verdict: "🟡 Probably Independent" },
  { name: "Tzin Wine & Tapas",    address: "10115 104 St NW, Edmonton, AB",            city: "Edmonton",     lat: 53.5433, lng: -113.4968, rating: 4.4, website: "https://tzin.ca",                    price_level: 3, indie_score:  6, positive_hits: ["seasonal menu","chef-driven","local farms"], negative_hits: [], supplier_hits: [],                          data_sources: ["website_main"],                 verdict: "🟡 Probably Independent" },

  // ── Ottawa ─────────────────────────────────────────────────────────────────
  { name: "The Whalesbone",       address: "430 Bank St, Ottawa, ON",                  city: "Ottawa",       lat: 45.4133, lng: -75.6931,  rating: 4.6, website: "https://thewhalesbone.com",          price_level: 3, indie_score: 12, positive_hits: ["locally sourced","ethically sourced","sustainable","seasonal menu","direct from farm"], negative_hits: [], supplier_hits: [], data_sources: ["website_main","website_about"], verdict: "🟢 Very Likely Independent" },
  { name: "Beckta",               address: "150 Elgin St, Ottawa, ON",                 city: "Ottawa",       lat: 45.4221, lng: -75.6908,  rating: 4.6, website: "https://beckta.com",                 price_level: 4, indie_score:  9, positive_hits: ["locally sourced","seasonal menu","ontario grown","chef-driven"], negative_hits: [], supplier_hits: [],           data_sources: ["website_main","website_about"], verdict: "🟡 Probably Independent" },
  { name: "play food & wine",     address: "1 York St, Ottawa, ON",                    city: "Ottawa",       lat: 45.4274, lng: -75.6953,  rating: 4.4, website: "https://playfoodandwine.com",        price_level: 3, indie_score:  7, positive_hits: ["seasonal menu","local farms","chef-driven","organic"], negative_hits: [], supplier_hits: [],                  data_sources: ["website_main"],                 verdict: "🟡 Probably Independent" },
  { name: "Arlo",                 address: "345 Preston St, Ottawa, ON",               city: "Ottawa",       lat: 45.4071, lng: -75.7085,  rating: 4.3, website: "https://arlorestaurant.ca",          price_level: 2, indie_score:  5, positive_hits: ["locally sourced","seasonal ingredients","house-made"], negative_hits: [], supplier_hits: [],             data_sources: ["website_main"],                 verdict: "🟡 Probably Independent" },

  // ── Montreal ───────────────────────────────────────────────────────────────
  { name: "Toqué!",               address: "900 Pl. Jean-Paul-Riopelle, Montreal, QC", city: "Montreal",     lat: 45.5080, lng: -73.5571,  rating: 4.8, website: "https://restaurant-toque.com",       price_level: 4, indie_score: 15, positive_hits: ["farm-to-table","locally sourced","quebec grown","our farmers","foraged","seasonal menu"], negative_hits: [], supplier_hits: ["ferme des 4 vents","fromagerie hamel"], data_sources: ["website_main","website_about"], verdict: "🟢 Very Likely Independent" },
  { name: "Joe Beef",             address: "2491 Rue Notre-Dame O, Montreal, QC",      city: "Montreal",     lat: 45.4740, lng: -73.5735,  rating: 4.7, website: "https://joebeef.com",                price_level: 4, indie_score: 11, positive_hits: ["locally sourced","quebec grown","seasonal menu","house-made","our farmers"], negative_hits: [], supplier_hits: [], data_sources: ["website_main","website_about"], verdict: "🟢 Very Likely Independent" },
  { name: "Au Pied de Cochon",    address: "536 Rue Duluth E, Montreal, QC",           city: "Montreal",     lat: 45.5231, lng: -73.5810,  rating: 4.6, website: "https://restaurantaupieddecochon.ca", price_level: 3, indie_score: 10, positive_hits: ["locally sourced","quebec farms","foraged","seasonal menu"], negative_hits: [], supplier_hits: [],         data_sources: ["website_main"],                 verdict: "🟢 Very Likely Independent" },
  { name: "Lawrence",             address: "5201 Blvd Saint-Laurent, Montreal, QC",    city: "Montreal",     lat: 45.5251, lng: -73.5981,  rating: 4.5, website: "https://lawrencerestaurant.com",     price_level: 3, indie_score:  8, positive_hits: ["locally sourced","seasonal menu","house-made","organic"], negative_hits: [], supplier_hits: [],             data_sources: ["website_main","website_about"], verdict: "🟡 Probably Independent" },
  { name: "Maison Publique",      address: "4720 Rue Marquette, Montreal, QC",         city: "Montreal",     lat: 45.5237, lng: -73.5750,  rating: 4.4, website: "https://maisonpublique.ca",           price_level: 2, indie_score:  7, positive_hits: ["seasonal menu","local farms","chef-driven"], negative_hits: [], supplier_hits: [],                         data_sources: ["website_main"],                 verdict: "🟡 Probably Independent" },

  // ── Quebec City ────────────────────────────────────────────────────────────
  { name: "Restaurant Initiale",  address: "54 Rue Saint-Pierre, Quebec City, QC",     city: "Quebec City",  lat: 46.8135, lng: -71.2020,  rating: 4.8, website: "https://restaurantinitiale.com",     price_level: 4, indie_score: 13, positive_hits: ["farm-to-table","locally sourced","quebec grown","seasonal menu","foraged","our farmers"], negative_hits: [], supplier_hits: [], data_sources: ["website_main","website_about"], verdict: "🟢 Very Likely Independent" },
  { name: "Le Clocher Penché",    address: "203 Rue Saint-Joseph E, Quebec City, QC",  city: "Quebec City",  lat: 46.8102, lng: -71.2184,  rating: 4.5, website: "https://clocherpenche.ca",           price_level: 3, indie_score: 10, positive_hits: ["locally sourced","quebec grown","seasonal menu","house-made"], negative_hits: [], supplier_hits: [],       data_sources: ["website_main","website_about"], verdict: "🟢 Very Likely Independent" },
  { name: "Toast!",               address: "17 Rue Sault-au-Matelot, Quebec City, QC", city: "Quebec City",  lat: 46.8156, lng: -71.2042,  rating: 4.4, website: "https://restauranttoast.com",        price_level: 3, indie_score:  8, positive_hits: ["local farms","seasonal menu","chef-driven","organic"], negative_hits: [], supplier_hits: [],                data_sources: ["website_main"],                 verdict: "🟡 Probably Independent" },

  // ── Winnipeg ───────────────────────────────────────────────────────────────
  { name: "Deer + Almond",        address: "85 Princess St, Winnipeg, MB",             city: "Winnipeg",     lat: 49.8959, lng: -97.1430,  rating: 4.6, website: "https://deerandalmond.com",          price_level: 3, indie_score: 10, positive_hits: ["locally sourced","seasonal menu","foraged","chef-driven","house-made"], negative_hits: [], supplier_hits: [], data_sources: ["website_main","website_about"], verdict: "🟢 Very Likely Independent" },
  { name: "Peasant Cookery",      address: "283 Bannatyne Ave, Winnipeg, MB",          city: "Winnipeg",     lat: 49.8945, lng: -97.1459,  rating: 4.4, website: "https://peasantcookery.ca",          price_level: 2, indie_score:  7, positive_hits: ["locally sourced","seasonal menu","small-batch","house-made"], negative_hits: [], supplier_hits: [],       data_sources: ["website_main"],                 verdict: "🟡 Probably Independent" },
  { name: "The Roost",            address: "545 Osborne St, Winnipeg, MB",             city: "Winnipeg",     lat: 49.8791, lng: -97.1416,  rating: 4.3, website: "https://theroostwinnipeg.com",       price_level: 2, indie_score:  6, positive_hits: ["local farms","seasonal ingredients","chef-driven"], negative_hits: [], supplier_hits: [],                  data_sources: ["website_main"],                 verdict: "🟡 Probably Independent" },

  // ── Halifax ────────────────────────────────────────────────────────────────
  { name: "Edna",                 address: "2053 Gottingen St, Halifax, NS",           city: "Halifax",      lat: 44.6567, lng: -63.5937,  rating: 4.7, website: "https://ednarestaurant.ca",          price_level: 3, indie_score: 11, positive_hits: ["locally sourced","atlantic farms","seasonal menu","ethically sourced","house-made"], negative_hits: [], supplier_hits: [], data_sources: ["website_main","website_about"], verdict: "🟢 Very Likely Independent" },
  { name: "Agricola St Brasserie",address: "2540 Agricola St, Halifax, NS",            city: "Halifax",      lat: 44.6607, lng: -63.5907,  rating: 4.4, website: "https://agricolabrasserie.ca",       price_level: 2, indie_score:  8, positive_hits: ["locally sourced","nova scotia farms","seasonal menu","chef-driven"], negative_hits: [], supplier_hits: [], data_sources: ["website_main"], verdict: "🟡 Probably Independent" },
  { name: "The Bicycle Thief",    address: "1475 Lower Water St, Halifax, NS",         city: "Halifax",      lat: 44.6458, lng: -63.5753,  rating: 4.3, website: "https://thebicyclethief.ca",         price_level: 3, indie_score:  6, positive_hits: ["local farms","seasonal ingredients","house-made"], negative_hits: [], supplier_hits: [],              data_sources: ["website_main"],                 verdict: "🟡 Probably Independent" },

  // ── Victoria ───────────────────────────────────────────────────────────────
  { name: "Olo",                  address: "509 Fisgard St, Victoria, BC",             city: "Victoria",     lat: 48.4301, lng: -123.3682, rating: 4.7, website: "https://olorestaurant.com",          price_level: 4, indie_score: 13, positive_hits: ["farm-to-table","locally sourced","bc grown","seasonal menu","foraged","our farmers"], negative_hits: [], supplier_hits: ["saltspring island cheese"], data_sources: ["website_main","website_about"], verdict: "🟢 Very Likely Independent" },
  { name: "The Courtney Room",    address: "619 Courtney St, Victoria, BC",            city: "Victoria",     lat: 48.4248, lng: -123.3658, rating: 4.5, website: "https://thecourtneyroom.com",        price_level: 4, indie_score:  9, positive_hits: ["locally sourced","bc farms","seasonal menu","chef-driven"], negative_hits: [], supplier_hits: [],           data_sources: ["website_main","website_about"], verdict: "🟡 Probably Independent" },
  { name: "Zambri's",             address: "820 Yates St, Victoria, BC",               city: "Victoria",     lat: 48.4255, lng: -123.3618, rating: 4.5, website: "https://zambris.ca",                 price_level: 3, indie_score:  7, positive_hits: ["locally sourced","seasonal menu","house-made","organic"], negative_hits: [], supplier_hits: [],             data_sources: ["website_main"],                 verdict: "🟡 Probably Independent" },
];

const { data, error } = await supabase.from("restaurants").insert(restaurants).select("name, city, indie_score");
if (error) { console.error("Insert failed:", error.message); process.exit(1); }

const byCity = {};
data.forEach(r => { byCity[r.city] = (byCity[r.city] || 0) + 1; });
console.log(`\nSeeded ${data.length} restaurants across ${Object.keys(byCity).length} new cities:\n`);
Object.entries(byCity).sort().forEach(([city, n]) => console.log(`  ${city}: ${n}`));

// Total check
const { count } = await supabase.from("restaurants").select("*", { count: "exact", head: true });
console.log(`\nTotal in database: ${count} restaurants`);
